---
title: "Lab 1"
author: "David Segan"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

Read in noaa_fisheries.csv data

```{r}
# us_landings <- read_csv("data/noaa_fisheries.csv")

us_landings <- read_csv(here("data","noaa_fisheries.csv"))

```

Now, make a tidy version of the data frame:

```{r}
landings_tidy <- us_landings %>% 
  janitor::clean_names() %>% 
  mutate(state = str_to_lower(state),
         afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_num = parse_number(dollars_usd))
```

Let's get some information for salmon only:
```{r}
salmon_landings <- landings_tidy %>% 
  mutate(afs_clean = str_remove(afs_name, pattern = "aggregate")) %>% # get rid of 'aggregate' word in afs_name
  filter(str_detect(afs_clean, pattern = "salmon")) %>%  # detects if world 'salmon' exists in afs_clean column, if yes return that row 
  separate(afs_clean,into = c("group", "species"), sep = ",") # splits afs_clean column into two columns, group & species. determing the split with commas
```

Find some grouped summary data:

Find annual total US landings and dollar value (summing across all states) for each TYPE of salmon using 'group_by()' and 'summarize()'

```{r}
salmon_summary <- salmon_landings %>% 
  group_by(year, species) %>% 
  summarize(tot_landings = sum(landings_pounds),
            tot_value = sum(dollars_num))
```

Graph

```{r}
salmon_landings_graph <- ggplot(data = salmon_summary,
                                aes(x = year, y = tot_landings, group = species)) +
  geom_line(aes(color = species)) +
  theme_minimal()

salmon_landings_graph

```

Now we'll export our graph with ggsave:
```{r}
ggsave(plot = salmon_landings_graph,
       here("figures", "us_salmon_ds.png"),
       height = 5,
       width = 8)
```

Make a nice kable table:
```{r}
salmon_first_10 <- salmon_summary %>% 
  head(10)
```

Use kable:
```{r}
kable(salmon_first_10) %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE)
```

